# Generated by Django 5.2.8 on 2026-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=150)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Temps plein', 'Temps plein'), ('Temps partiel', 'Temps partiel')], max_length=50)),
                ('departement', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('missions', models.TextField()),
                ('profil', models.TextField()),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
