# Generated by Django 5.2.8 on 2026-06-08 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('poste', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='carrieres/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='carrieres/lettres/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='ZenerApp.joboffer')),
            ],
        ),
    ]
