# Generated by Django 5.2.8 on 2026-06-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0002_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_offer',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='poste',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='ZenerApp.joboffer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='candidatures/cv/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/lettres/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
