# Generated by Django 5.2.8 on 2026-06-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='ZenerApp.joboffer'),
        ),
    ]
