# Generated by Django 5.2.8 on 2026-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0005_alter_jobapplication_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='traitee',
            field=models.BooleanField(default=False),
        ),
    ]
