# Generated by Django 5.2.8 on 2026-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0006_jobapplication_traitee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeZenCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=100)),
                ('type_demande', models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=20)),
                ('station_retrait', models.CharField(choices=[('Zener Hedzranawoe', 'Zener Hedzranawoe'), ('Zener Adidogome', 'Zener Adidogome'), ('Zener Agoe', 'Zener Agoe'), ('Zener GTA', 'Zener GTA'), ('Zener Port', 'Zener Port'), ('Zener Baguida', 'Zener Baguida'), ('Zener Kpalime', 'Zener Kpalime'), ('Zener Atakpame', 'Zener Atakpame'), ('Zener Sokode', 'Zener Sokode'), ('Zener Kara', 'Zener Kara'), ('Zener Dapaong', 'Zener Dapaong')], max_length=100)),
                ('cni', models.ImageField(upload_to='zencard/cni/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
