# Generated by Django 5.2.8 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenerApp', '0007_demandezencard'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandezencard',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20),
        ),
    ]
